- name: Create a PostgreSQL Cluster
  hosts: all
  vars:
    openshift_project: postgres-example
    postgres_cluster_name: postgres-cluster
    openshift_api: https://api.ocp4.example.com:6443
    openshift_user: admin
    openshift_password: admin1234
  tasks:
    - name: Log in to OpenShift
      command: >
        oc login {{ openshift_api }} --username={{ openshift_user }} --password={{ openshift_password }} --insecure-skip-tls-verify
      changed_when: false

    - name: Check if OpenShift Project Exists
      command: oc get project {{ openshift_project }}
      register: project_exists
      failed_when: false
      changed_when: false

    - name: Create OpenShift Project if it does not exist
      command: oc new-project {{ openshift_project }}
      when: "'Active' not in project_exists.stdout"

    - name: Template PostgreSQL yaml file
      set_fact:
        postgres_yaml: "{{ lookup('template', 'templates/postgres_cluster.yml.j2') }}"

    - name: Create PostgreSQL cluster
      command: oc apply -f -
      args:
        stdin: "{{ postgres_yaml }}"
      changed_when: true
